version: "0.1"
user: onpremezztt
key: LT_ry2st1BzTpPPhWDaEnUGtdQC09Ixq5uDQV6rJ3Mpb1FxVdN
testSuites: []
pre: [echo "Starting Test...", 'mvn dependency:resolve -Dmaven.repo.local=.m2']
preDirectives:
    commands: [echo "Starting Test...", 'mvn dependency:resolve -Dmaven.repo.local=.m2']
    maxRetries: 0
    shell: ""
    workingDirectory: ""
postDirectives:
    commands: []
    shell: ""
    workingDirectory: ""
jobLabel:
    - QAF
    - Linux
    - AutoSplit
    - 'Features: All'
runson: linux
autosplit: true
concurrency: 4
testDiscovery:
    command: snooper --targetOs=mac --featureFilePaths=resources/features/ --frameWork=java | sed 's/:.*//' | uniq
    mode: remote
    type: raw
testRunnerCommand: |
    echo "Running test: $test"
    mvn test -Dmaven.repo.local=.m2 -Dsurefire.suiteXmlFiles=testNG_BDD.xml -Dscenario.file.loc="$test"
tunnelOpts:
    testsPerTunnel: 10
cacheDirectories:
    - .m2
cacheKey: '{{ checksum "pom.xml" }}'
jobID: 24b70bc6-5040-4b02-8ec0-c5e84332bb77
codeDirectory: BandWidth
framework:
    name: ""
    flags: []
    discoveryFlags: []
    discoveryMode: ""
    discoveryType: ""
    runnerFlags: []
    workingDirectory: ""
    isTestNGXMLSuite: false
    defaultReports: false
    args:
        appPath: ""
        testSuitePath: ""
        xcTestPlanPath: ""
        shards:
            mappings: []
        filters:
            attributes: []
        devices: []
        deviceSelectionStrategy: ""
        appId: ""
        testSuiteAppId: ""
        xcTestPlanId: ""
        skipXMLOnRun: false
        skipInstall: false
        disableReleaseDevice: false
        platformName: ""
        isRealMobile: null
        avoidAppLaunch: false
        queueTimeout: 0
        uninstallPreviousBuild: false
        language: ""
        locale: ""
        preservedDevice: false
        fixedIP: ""
        resignApp: true
        minorOsVersion: false
        playwrightRD: false
        mobileDC: null
        skipUninstallPreviousBuild: false
        isVirtualDevice: false
        mitmProxy: false
        networkHar: false
        artifacts: false
        otherApps: []
    additional_args: null
    licenseKey: ""
    userdefinediscovery: false
    toscaArgs: null
    version: ""
    downloadURL: ""
    baseCommand: ""
cypress: false
betaFeature:
    setPartiallyCompletedAsCompleted: false
combineTasksInMatrixMode: false
captureScreenRecordingForScenarios: false
maxRetriesPreSteps: 0
triggerMode: false
sourcePayload:
    verifySSL: true
collectLocalGitData: false
dynamicAllocation: false
appium: false
platformConfig: null
differentialUpload:
    enabled: true
    ttlHours: 24
    forcedDisabled: false
project:
    id: 01JV6TNBK0NBBG852GWQTZCVD7
    name: Dhakshath11/BandWidth_QAF
    type: custom
meta: {}
alwaysRunPostSteps: false
errorCategorizedOnFailureOnly: false
testDiscoveryResultV3: []
storageType: ""
localHTTPProxy: ""
regionConfig:
    vm: []
    storage:
        region: ""
        enabled: false
        name: ""
        platform: azure
waitForArtefactsUpload: false
unzipPayload: false
projectpath: ""
accessibilityJob: false
globalPre:
    mode: ""
    commands: []
    maxRetries: 0
    shell: ""
    workingDirectory: ""
    completed: false
    runson: ""
globalPost:
    mode: ""
    commands: []
    shell: ""
    workingDirectory: ""
    completed: false
    runson: ""
slackChannel: ""
whiteLabelProductTag: ""
