accessibilityJob: false
alwaysRunPostSteps: false
appium: null
autosplit: true
betaFeature:
    setPartiallyCompletedAsCompleted: false
cacheDirectories:
    - .m2
cacheKey: '{{ checksum "pom.xml" }}'
captureScreenRecordingForScenarios: false
codeDirectory: BandWidth
collectLocalGitData: true
combineTasksInMatrixMode: false
concurrency: 4
cypress: false
differentialUpload:
    enabled: true
    forcedDisabled: false
    ttlHours: 24
dynamicAllocation: false
errorCategorizedOnFailureOnly: false
framework:
    additional_args: null
    args:
        appId: ""
        appPath: ""
        artifacts: false
        avoidAppLaunch: false
        customData: {}
        deviceSelectionStrategy: ""
        devices: []
        disableReleaseDevice: false
        filters:
            attributes: []
        fixedIP: ""
        isRealMobile: null
        isVirtualDevice: false
        language: ""
        locale: ""
        minorOsVersion: false
        mitmProxy: false
        mobileDC: null
        networkHar: false
        otherApps: []
        platformName: ""
        playwrightRD: false
        preservedDevice: false
        queueTimeout: 0
        resignApp: true
        shards:
            mappings: []
        skipInstall: false
        skipUninstallPreviousBuild: false
        skipXMLOnRun: false
        smartUI: null
        testSuiteAppId: ""
        testSuitePath: ""
        uninstallPreviousBuild: false
        xcTestPlanId: ""
        xcTestPlanPath: ""
    baseCommand: ""
    defaultReports: false
    discoveryFlags: []
    discoveryMode: ""
    discoveryType: ""
    downloadURL: ""
    flags: []
    isTestNGXMLSuite: false
    licenseKey: ""
    name: maven/testng
    runnerFlags: []
    toscaArgs: null
    userdefinediscovery: false
    version: ""
    workingDirectory: ""
globalPost:
    commands: []
    completed: false
    mode: ""
    runson: ""
    shell: ""
    workingDirectory: ""
globalPre:
    cache: false
    commands: []
    completed: false
    location: ""
    maxRetries: 0
    mode: ""
    runson: ""
    shell: ""
    type: ""
    workingDirectory: ""
    yamlPath: null
jobID: 8ea7d4d1-d8d9-4c1a-86bb-8dc63f1f1284
jobLabel:
    - Testing
    - CrossBrowserSuite
    - AutoSplit
key: LT_Pf3gLJhEz0t7X2h7gQca0y2fAzQJVUl6SwRxPNPlsPatcXf
localHTTPProxy: ""
maxRetriesPreSteps: 0
meta: {}
platformConfig: null
postDirectives:
    commands: []
    shell: ""
    workingDirectory: ""
pre:
    - echo Starting Test...
    - mvn dependency:resolve -Dmaven.repo.local=.m2
preDirectives:
    commands:
        - echo Starting Test...
        - mvn dependency:resolve -Dmaven.repo.local=.m2
    maxRetries: 0
    shell: ""
    workingDirectory: ""
project:
    id: 01JTJ6ZDY0X89X19CZVS30ZS4F
    name: Test Project Auto
    type: custom
projectpath: ""
regionConfig:
    storage:
        enabled: false
        name: ""
        platform: azure
        region: ""
    vm: []
report: true
runson: mac
runtime:
    language: java
    version: "11"
    addons: []
    opts: {}
slackChannel: ""
sourcePayload:
    verifySSL: true
sprofilePath: ""
storageType: ""
testDiscovery:
    command: grep "test name" testng_Auto.xml | awk '{print$2}' | sed 's/name=//g' | sed 's/\x3e//g'
    mode: remote
    type: raw
testDiscoveryResultV3: []
testRunnerCommand: |
    echo "Generating selected_testng.xml for test: $test"
    mvn test -Denv="lambdaTest" -Dmaven.repo.local=.m2 -DselectedTests=$test -Dsurefire.suiteXmlFiles=testNG_Auto.xml
testSuites: []
triggerMode: false
tunnelOpts:
    testsPerTunnel: 10
unzipPayload: false
user: dhakshathamin
version: "0.1"
waitForArtefactsUpload: false
whiteLabelProductTag: ""
