accessibilityJob: false
alwaysRunPostSteps: false
appium: false
autosplit: true
betaFeature:
    setPartiallyCompletedAsCompleted: false
cacheDirectories:
    - .m2
cacheKey: '{{ checksum "pom.xml" }}'
captureScreenRecordingForScenarios: false
codeDirectory: BandWidth
collectLocalGitData: false
combineTasksInMatrixMode: false
concurrency: 4
cypress: false
differentialUpload:
    enabled: true
    forcedDisabled: false
    ttlHours: 24
dynamicAllocation: false
errorCategorizedOnFailureOnly: false
framework:
    additional_args: null
    args:
        appId: ""
        appPath: ""
        artifacts: false
        avoidAppLaunch: false
        deviceSelectionStrategy: ""
        devices: []
        disableReleaseDevice: false
        filters:
            attributes: []
        fixedIP: ""
        isRealMobile: null
        isVirtualDevice: false
        language: ""
        locale: ""
        minorOsVersion: false
        mitmProxy: false
        mobileDC: null
        networkHar: false
        otherApps: []
        platformName: ""
        playwrightRD: false
        preservedDevice: false
        queueTimeout: 0
        resignApp: true
        shards:
            mappings: []
        skipInstall: false
        skipUninstallPreviousBuild: false
        skipXMLOnRun: false
        testSuiteAppId: ""
        testSuitePath: ""
        uninstallPreviousBuild: false
        xcTestPlanId: ""
        xcTestPlanPath: ""
    baseCommand: ""
    defaultReports: false
    discoveryFlags: []
    discoveryMode: ""
    discoveryType: ""
    downloadURL: ""
    flags: []
    isTestNGXMLSuite: false
    licenseKey: ""
    name: ""
    runnerFlags: []
    toscaArgs: null
    userdefinediscovery: false
    version: ""
    workingDirectory: ""
globalPost:
    commands: []
    completed: false
    mode: ""
    runson: ""
    shell: ""
    workingDirectory: ""
globalPre:
    commands: []
    completed: false
    maxRetries: 0
    mode: ""
    runson: ""
    shell: ""
    workingDirectory: ""
jobID: faeefefc-6d27-4419-9daf-ba9686885fec
jobLabel:
    - QAF
    - Linux
    - AutoSplit
    - 'Features: All'
key: LT_ry2st1BzTpPPhWDaEnUGtdQC09Ixq5uDQV6rJ3Mpb1FxVdN
localHTTPProxy: ""
maxRetriesPreSteps: 0
meta: {}
platformConfig: null
postDirectives:
    commands: []
    shell: ""
    workingDirectory: ""
pre:
    - echo "Starting Test..."
    - mvn dependency:resolve -Dmaven.repo.local=.m2
    - printenv
    - echo $LT_USERNAME and $LT_ACCESS_KEY
preDirectives:
    commands:
        - echo "Starting Test..."
        - mvn dependency:resolve -Dmaven.repo.local=.m2
        - printenv
        - echo $LT_USERNAME and $LT_ACCESS_KEY
    maxRetries: 0
    shell: ""
    workingDirectory: ""
project:
    id: 01JV6TNBK0NBBG852GWQTZCVD7
    name: Dhakshath11/BandWidth_QAF
    type: custom
projectpath: ""
regionConfig:
    storage:
        enabled: false
        name: ""
        platform: azure
        region: ""
    vm: []
runson: linux
runtime:
    language: java
    version: "11"
    addons: []
    opts: {}
slackChannel: ""
sourcePayload:
    verifySSL: true
storageType: ""
testDiscovery:
    command: snooper --targetOs=mac --featureFilePaths=resources/features/ --frameWork=java | sed 's/:.*//' | uniq
    mode: remote
    type: raw
testDiscoveryResultV3: []
testRunnerCommand: |
    echo "Running test: $test"
    mvn test -Dmaven.repo.local=.m2 -Dsurefire.suiteXmlFiles=testNG_BDD.xml -Dscenario.file.loc="$test" -Dremote.server=$LT_USERNAME:$LT_ACCESS_KEY@hub.lambdatest.com -Dchrome.additional.capabilities='{"LT:Options":{"build":"QAF Execution","name":"QAF-chrome","browserVersion":"latest","network":true,"console":true,"screenResolution":"2560x1440","selenium_version":"4.27.0"}}'
testSuites: []
triggerMode: false
tunnelOpts:
    testsPerTunnel: 10
unzipPayload: false
user: onpremezztt
version: "0.1"
waitForArtefactsUpload: false
whiteLabelProductTag: ""
